### ISSUE TITLE
Add unit tests for new mass and cost models

### ISSUE THREAD

**Issue by dykesk** [WISDEM/Turbine_CostsSE#3]
Need to add unit tests for the new turbine costs models - wait for openmdao 1.0

**Comment by kilojoules** [comment]
I added a unit test in 3a8e9bb56fc601e3aa2d90b390b84a0fdcd6c199. Should the Mainframe cost be negative?

    $ python turbine_costsse_2015.py 
    The results for the NREL 5 MW Reference Turbine in an offshore 20 m water depth location are:
    
    Overall rotor cost with 3 advanced blades is $1292397.85 USD
    Blade cost is $257699.78 USD
    Hub cost is $123413.55 USD
    Pitch system cost is $375788.40 USD
    Spinner cost is $20096.55 USD
    
    Overall nacelle cost is $1834597.19 USD
    LSS cost is $371961.87 USD
    Main bearings cost is $43791.35 USD
    Gearbox cost is $390065.04 USD
    High speed side cost is $10148.66 USD
    Generator cost is $207078.14 USD
    Bedplate cost is $269962.74 USD
    Yaw system cost is $98589.39 USD
    Variable speed electronics cost is $18800.00 USD
    HVAC cost is $124000.00 USD
    Electrical connections cost is $209250.00 USD
    Controls cost is $105750.00 USD
    Mainframe cost is $-39300.00 USD
    Transformer cost is $18800.00 USD
    
    Tower cost is $1260221.10 USD
    
    The overall turbine cost is $4387216.13 USD

**Comment by dykesk** [comment]
Updated the masses in the example to be more realistic so mainframe cost is now positive - tests updated to check this as well
