### ISSUE TITLE
Errors on Turbine_CostsSE test

### ISSUE THREAD

**Issue by JTYoon** [WISDEM/Turbine_CostsSE#6]
My name is Joung T. Yoon and I want to use "Turbine_CostsSE" for me research.
First of all, I really appreciate for your software. It really helps my research.

I have installed "Turbine_CostsSE" but have errors in "test_Turbine_CostsSE".
The error messages are like below.
================= Error message start =====================
(devenv) C:\Python27\Turbine_CostsSE>python src/test/test_Turbine_CostsSE.py

.
**\* Warning: BearingsCost does not supply derivatives for the following
        inputs: ['month', 'year']
        outputs: []

..
**\* Warning: BedplateCost does not supply derivatives for the following
        inputs: ['month', 'drivetrain_design', 'year']
        outputs: []

..
**\* Warning: BladeCost does not supply derivatives for the following
        inputs: ['month', 'advanced', 'year']
        outputs: []

..
**\* Warning: GearboxCost does not supply derivatives for the following
        inputs: ['month', 'drivetrain_design', 'year']
        outputs: []

..
**\* Warning: GeneratorCost does not supply derivatives for the following
        inputs: ['month', 'drivetrain_design', 'year']
        outputs: []

..
**\* Warning: HighSpeedSideCost does not supply derivatives for the following
        inputs: ['month', 'year']
        outputs: []

..
**\* Warning: HubCost does not supply derivatives for the following
        inputs: ['month', 'year']
        outputs: []

....
**\* Warning: LowSpeedShaftCost does not supply derivatives for the following
        inputs: ['month', 'year']
        outputs: []

.F
**\* Warning: NacelleSystemCostAdder does not supply derivatives for the followin
g
        inputs: ['crane', 'year', 'offshore', 'month']
        outputs: []

.F.
**\* Warning: PitchSystemCost does not supply derivatives for the following
        inputs: ['month', 'year']
        outputs: []

..
**\* Warning: RotorCostAdder does not supply derivatives for the following
        inputs: ['blade_number']
        outputs: []

.FF
**\* Warning: SpinnerCost does not supply derivatives for the following
        inputs: ['month', 'year']
        outputs: []

..
**\* Warning: TowerCost does not supply derivatives for the following
        inputs: ['month', 'year']
        outputs: []

.....
**\* Warning: TurbineCostAdder does not supply derivatives for the following
        inputs: ['overheadCostMultiplier', 'transportMultiplier', 'assemblyCostM
ultiplier', 'offshore', 'profitMultiplier']
        outputs: []

.
**\* EM 12 > LER 8 in table 334513
E.
**\* Warning: YawSystemCost does not supply derivatives for the following
        inputs: ['month', 'year']
        outputs: []

.F
**\* Warning: blades_csm_component does not supply derivatives for the following
        inputs: ['month', 'year', 'advanced_blade']
        outputs: []

.F
**\* Warning: hub_csm_component does not supply derivatives for the following
        inputs: ['month', 'blade_number', 'year']
        outputs: []

.F
**\* Warning: nacelle_csm_component does not supply derivatives for the following

```
    inputs: ['month', 'advanced_bedplate', 'drivetrain_design', 'year', 'cra
```

ne', 'offshore']
        outputs: []

..
**\* Warning: rotor_mass_adder does not supply derivatives for the following
        inputs: ['blade_number']
        outputs: []

.F.
**\* Warning: tower_csm_component does not supply derivatives for the following
        inputs: ['advanced_tower', 'month', 'year']
        outputs: []
# .
## ERROR: test_functionality (**main**.TestTurbine_CostSE)

Traceback (most recent call last):
  File "src/test/test_Turbine_CostsSE.py", line 484, in test_functionality
    self.turbine.run()
  File "c:\python27\openmdao-framework-0.10.3.2\openmdao.main\src\openmdao\main\
component.py", line 557, in run
    self.execute()
  File "c:\python27\openmdao-framework-0.10.3.2\openmdao.main\src\openmdao\main\
assembly.py", line 769, in execute
    self.driver.run(ffd_order=self.ffd_order, case_uuid=self._case_uuid)
  File "c:\python27\openmdao-framework-0.10.3.2\openmdao.main\src\openmdao\main\
driver.py", line 312, in run
    super(Driver, self).run(ffd_order, case_uuid)
  File "c:\python27\openmdao-framework-0.10.3.2\openmdao.main\src\openmdao\main\
component.py", line 557, in run
    self.execute()
  File "c:\python27\openmdao-framework-0.10.3.2\openmdao.main\src\openmdao\main\
driver.py", line 336, in execute
    self.run_iteration()
  File "c:\python27\openmdao-framework-0.10.3.2\openmdao.main\src\openmdao\main\
driver.py", line 367, in run_iteration
    wf.run(ffd_order=self.ffd_order)
  File "c:\python27\openmdao-framework-0.10.3.2\openmdao.main\src\openmdao\main\
workflow.py", line 141, in run
    comp.run(ffd_order=ffd_order, case_uuid=case_uuid)
  File "c:\python27\openmdao-framework-0.10.3.2\openmdao.main\src\openmdao\main\
component.py", line 557, in run
    self.execute()
  File "c:\python27\openmdao-framework-0.10.3.2\openmdao.main\src\openmdao\main\
assembly.py", line 769, in execute
    self.driver.run(ffd_order=self.ffd_order, case_uuid=self._case_uuid)
  File "c:\python27\openmdao-framework-0.10.3.2\openmdao.main\src\openmdao\main\
driver.py", line 312, in run
    super(Driver, self).run(ffd_order, case_uuid)
  File "c:\python27\openmdao-framework-0.10.3.2\openmdao.main\src\openmdao\main\
component.py", line 557, in run
    self.execute()
  File "c:\python27\openmdao-framework-0.10.3.2\openmdao.main\src\openmdao\main\
driver.py", line 336, in execute
    self.run_iteration()
  File "c:\python27\openmdao-framework-0.10.3.2\openmdao.main\src\openmdao\main\
driver.py", line 367, in run_iteration
    wf.run(ffd_order=self.ffd_order)
  File "c:\python27\openmdao-framework-0.10.3.2\openmdao.main\src\openmdao\main\
workflow.py", line 141, in run
    comp.run(ffd_order=ffd_order, case_uuid=case_uuid)
  File "c:\python27\openmdao-framework-0.10.3.2\openmdao.main\src\openmdao\main\
component.py", line 557, in run
    self.execute()
  File "c:\python27\turbine_costsse\src\turbine_costsse\turbine_costsse.py", lin
e 996, in execute
    controlsCostEsc      = ppi.compute('IPPI_CTL')
  File "c:\python27\commonse\src\commonse\csmPPI.py", line 266, in compute
    esc = self.escData[escCode].compute(self.ppitbls,self.ref_yr,self.ref_mon,se
lf.curr_yr,self.curr_mon)
  File "c:\python27\commonse\src\commonse\csmPPI.py", line 48, in compute
    ce = ppitbls[key].getEsc(sy,sm,ey,em)
  File "c:\python27\commonse\src\commonse\csmPPI.py", line 84, in getEsc
    raise IndexError("End_mon out of range")
IndexError: End_mon out of range
# 
## FAIL: test_functionality (**main**.TestNacelleSystemCostAdder)

Traceback (most recent call last):
  File "src/test/test_Turbine_CostsSE.py", line 445, in test_functionality
    self.assertEqual(round(self.nacelle.cost,2), 2917983.91)
AssertionError: 2835711.05 != 2917983.91
# 
## FAIL: test_functionality (**main**.TestNacelle_CostSE)

Traceback (most recent call last):
  File "src/test/test_Turbine_CostsSE.py", line 267, in test_functionality
    self.assertEqual(round(self.nacelle.cost,2), 2917983.93)
AssertionError: 2835711.06 != 2917983.93
# 
## FAIL: test_functionality (**main**.TestRotor_CostSE)

Traceback (most recent call last):
  File "src/test/test_Turbine_CostsSE.py", line 110, in test_functionality
    self.assertEqual(round(self.rotor.cost,2), 1478411.14)
AssertionError: 1475238.79 != 1478411.14
# 
## FAIL: test_functionality (**main**.TestSpinnerCost)

Traceback (most recent call last):
  File "src/test/test_Turbine_CostsSE.py", line 190, in test_functionality
    self.assertEqual(round(self.spinner.cost,2), 10508.99)
AssertionError: 7336.64 != 10508.99
# 
## FAIL: test_functionality (**main**.Test_blade_csm_component)

Traceback (most recent call last):
  File "src/test/test_Turbine_CostsSE.py", line 556, in test_functionality
    self.assertEqual(round(self.blades.blade_cost,2), 276143.07)
AssertionError: 21684.82 != 276143.07
# 
## FAIL: test_functionality (**main**.Test_hub_csm_component)

Traceback (most recent call last):
  File "src/test/test_Turbine_CostsSE.py", line 579, in test_functionality
    self.assertEqual(round(self.hub.hub_system_cost,2), 421290.41)
AssertionError: 418118.06 != 421290.41
# 
## FAIL: test_functionality (**main**.Test_nacelle_csm_component)

Traceback (most recent call last):
  File "src/test/test_Turbine_CostsSE.py", line 610, in test_functionality
    self.assertEqual(round(self.nac.nacelle_cost,2), 3275147.05)
AssertionError: 3192874.18 != 3275147.05
# 
## FAIL: test_functionality (**main**.Test_tcc_csm_assembly)

Traceback (most recent call last):
  File "src/test/test_Turbine_CostsSE.py", line 673, in test_functionality
    self.assertEqual(round(self.trb.turbine_cost,2), 5925727.43)
AssertionError: 4992025.48 != 5925727.43

---

Ran 49 tests in 0.630s

FAILED (failures=8, errors=1)
================= Error message end =====================

It looks there are two main problems:
1) The derivatives of inputs and outputs are not supplied.
2) "assertEqual" test is not passed. (precision problem?)

Could you please advise me for it?
Thank you in advance. : )

Installed environment
- Windows 7 64-bit
- Python 2.7 (32-bit)
- OpenMDAO-Framework-0.10.3.2
- CommonSE
- FusedWind
- Turbine_CostsSE
- Other modules of Python (Numpy, Scipy, ...)

**Comment by JTYoon** [comment]
One more question please.
For the Turbine_CostsSe, is there any difference between OpenMDAO-Framework(0.10.3.2) and OpenMDAO(0.10.3.2)?
Is it okay to use OpenMDAO(0.10.3.2)?

**Comment by kilojoules** [comment]
Use this OpenMDAO [http://openmdao.org/releases/0.13.0/](http://openmdao.org/releases/0.13.0/)

It looks like a CommonSE error and doesn't show up when I run the test. Could you please try running `python src/commonse/test/test_environment_gradients.py ` in the CommonSE folder?
